spring:
  application:
    name: persea-product-service
  datasource:
      url: jdbc:postgresql://localhost:5432/product_service
      username: myuser
      password: mypassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/persea
  data:
    web:
      pageable:
        max-page-size: 50
        default-page-size: 20
      sort:
        sort-parameter: name

server:
  port: 8083

logging:
  level:
    org:
      springframework:
        security: INFO