spring:
  application:
    name: persea-product-service
  datasource:
      url: jdbc:postgresql://localhost:5432/product_service
      username: postgres
      password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/persea
  elasticsearch:
    uris: http://localhost:9200

server:
  port: 8083

logging:
  level:
    org:
      springframework:
        security: INFO
app:
  default-autocomplete-suggestions: 5