spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/product_service
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080/realms/persea
  elasticsearch:
    uris: http://elasticsearch:9200

